<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>com.gastroblue</groupId>
		<artifactId>gastroblue-parent</artifactId>
		<version>1.0.4</version>
	</parent>

	<artifactId>identity-service</artifactId>
	<version>1.0.0</version>
	<name>identity-service</name>
	<description>GastroBlue identity and authentication service</description>

	<dependencies>

		<dependency>
			<groupId>org.postgresql</groupId>
			<artifactId>postgresql</artifactId>
			<scope>runtime</scope>
		</dependency>

		<dependency>
			<groupId>com.gastroblue</groupId>
			<artifactId>gastroblue-commons</artifactId>
			<version>1.6.20</version>
		</dependency>

	</dependencies>

	<repositories>
		<repository>
			<id>github</id>
			<url>https://maven.pkg.github.com/hakanguneser/gastroblue-commons</url>
		</repository>
	</repositories>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
			<plugin>
				<groupId>com.diffplug.spotless</groupId>
				<artifactId>spotless-maven-plugin</artifactId>
			</plugin>
		</plugins>
	</build>

</project>
