spring:
  application:
    name: identity-service

  datasource:
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:identity}
    username: ${DATABASE_USERNAME:identity_admin}
    password: ${DATABASE_PASSWORD:postgres}
    hikari:
      connection-init-sql: SET TIMEZONE TO 'Europe/Istanbul'
      pool-name: node-adapter-hikari
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: false
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      validation-timeout: 5000
      connection-test-query: SELECT 1

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: ${SERVER_PORT:7102}


management:
  endpoints:
    web:
      exposure:
        include: health, prometheus, metrics


app:
  admin:
    registration:
      enabled: ${APP_ADMIN_REGISTRATION_ENABLED:true}
  expo:
    base-url: ${EXPO_PUSH_BASE_URL:https://exp.host}
    access-token: ${EXPO_ACCESS_TOKEN:}

mail:
  enabled: ${MAIL_ENABLED:true}
  from: ${MAIL_FROM}
  admin-redirect-address: ${MAIL_ADMIN_REDIRECT_ADDRESS:hakan.guneser@gmail.com}
  smtp:
    host: ${MAIL_SMTP_HOST:smtp.gmail.com}
    port: ${MAIL_SMTP_PORT:587}
    username: ${MAIL_FROM}
    password: ${MAIL_PASSWORD}

gastroblue:
  identity:
    token:
      private-key: ${EC_PRIVATE_KEY:MEECAQAwEwYHKoZIzj0CAQYIKoZIzj0DAQcEJzAlAgEBBCC6MSk5LiOmSnpOyrNo2ID/GtPU2eAqHsN3shEHWPQOaw==}
  commons:
    security:
      enabled: true
      public-key: ${EC_PUBLIC_KEY:MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE3AQzd7jGIvnvtHORNZ17vPPJEAlb1kfOmPfLr6HNOoJvutGvz4qhKgd8HPYLttVBWI50txLF/08sFsQRwqpw/Q==}
      token-validity-in-minutes: ${JWT_TOKEN_VALIDITY_IN_MINUTES:60}
      refresh-token-validity-in-days: ${JWT_REFRESH_TOKEN_VALIDITY_IN_DAYS:7}
      sys-tokens:
        tracker:
          token: ${TRACKER_TOKEN:TRACKER_TOKEN_NOT_CONFIGURED}
          product: TRACKER
        formflow:
          token: ${FORMFLOW_TOKEN:FORMFLOW_TOKEN_NOT_CONFIGURED}
          product: FORMFLOW
        admin:
          token: ${ADMIN_TOKEN:ADMIN_TOKEN_NOT_CONFIGURED}
          product: CHECK
    tracing:
      enabled: true
    exception:
      enabled: true
    swagger:
      enabled: true
      title: Identity Service API
      version: 1.0
      description: GastroBlue kimlik doğrulama servisi
      contact:
        name: Hakan Guneser
        email: hakanguneser@gastroblueapp.com
        url: https://www.gastrobluecheckapp.com/