package com.gastroblue.model.enums;

public enum ErrorCode {
  USER_NOT_ALLOWED_FOR_REGISTRATION,
  USER_NOT_FOUND,
  USER_ALREADY_EXISTS,
  INVALID_REQUEST_BODY,
  COMPANY_MISMATCH,
  USER_EMAIL_NOT_FOUND,
  UNAUTHORIZED_USER,
  ACCESS_DENIED,
  INVALID_USERNAME_OR_PASSWORD,
  DATA_INTEGRITY_VIOLATION,
  INVALID_ENUM_VALUE,
  ADMINISTRATOR_REGISTRATION_DISABLED,
  EXPIRED_JWT_TOKEN,
  ILLEGAL_DEFINITION,
  COMPANY_GROUP_BULK_INSERT_EXCEPTION,
  CONFIGURATION_NOT_FOUND;
}
