package com.gastroblue.model.enums;

import com.gastroblue.util.enums.IDisplayableEnum;
import lombok.AllArgsConstructor;
import lombok.Getter;

@Getter
@AllArgsConstructor
public enum ErrorCode implements IDisplayableEnum {
  COMPANY_NOT_FOUND,
  USER_NOT_ALLOWED_FOR_REGISTRATION,
  COMPANY_MASTER_FORM_NOT_FOUND,
  COMPANY_FORM_DETAIL_NOT_FOUND,
  FORM_NOT_FOUND,
  USER_NOT_FOUND,
  USER_ALREADY_EXISTS,
  COMPANY_FORM_DEFINITION_ALREADY_EXISTS,
  COMPANY_FORM_DEFINITION_NOT_FOUND,
  FORM_DEFINITION_NOT_FOUND,
  MEASUREMENT_DEFINITION_NOT_FOUND,
  DUPLICATE_MEASUREMENT_ORDER,
  NULL_MEASUREMENT_ORDER,
  DUPLICATE_THERMOMETER_CODE,
  DUPLICATE_ASSET_NAME,
  QUESTION_DEFINITION_NOT_FOUND,
  INVALID_QUESTIONNAIRE_ENTRY,
  ID_CANNOT_BE_NULL,
  ID_CANNOT_BE_DUPLICATED,
  DEFINITION_ALREADY_INACTIVE,
  LOGIN_FAILED,
  INVALID_FORM_TYPE,
  ERROR_CODE_NOT_FOUND,
  FORM_ALREADY_SUBMITTED,
  FORM_ALREADY_APPROVED,
  INVALID_REQUEST_BODY,
  ENTITY_SAVE_FAILED,
  INVALID_MEASUREMENT_FORM_ENTRY,
  ASSET_NAME_REQUIRED,
  ASSET_LIST_REQUIRED,
  CANNOT_UPDATE_INACTIVE_DEFINITION,
  DAILY_ACTIVITY_FORM_NOT_FOUND,
  COMPANY_MISMATCH,
  USER_EMAIL_NOT_FOUND,
  MAIL_TEMPLATE_NOT_FOUND,
  MAIL_TEMPLATE_NOT_APPROVED,
  UNAUTHORIZED_USER,
  ACCESS_DENIED,
  INVALID_TEMPERATURE_CONFIGURATION,
  INVALID_USERNAME_OR_PASSWORD,
  DATA_INTEGRITY_VIOLATION,
  INVALID_ENUM_VALUE,
  ADMINISTRATOR_REGISTRATION_DISABLED,
  INSUFFICIENT_APPROVAL_PRIVILEGES,
  FORM_SUBMISSION_RESTRICTED,
  INCOMPLETE_FORM_SUBMISSION,
  PREVIOUS_SUBMISSIONS_MISSING,
  EXPIRED_JWT_TOKEN,
  SYSTEM_ERROR,
  UNAPPROVED_FORM_CANNOT_NOTIFY,
  INVALID_DATE_RANGE,
  INVALID_TASK_CODE,
  TASK_DEFINITION_NOT_FOUND,
  PLANNING_DEPARTMENTS_REQUIRED,
  PPF_CANNOT_ASSIGN_TO_STAFF_ROLE,
  PPF_CAN_FILL_ONCE_FOR_PERSONNEL_GROUP,
  PLANNING_DEPARTMENTS_ALREADY_DEFINED,
  PERSONNEL_PLANNING_FORM_DEFINITION_NOT_FOUND,
  PERSONNEL_PLANNING_FORM_ALREADY_EXISTS,
  EMPTY_ITEMS,
  DUPLICATE_INDEX,
  DUPLICATE_ID,
  ILLEGAL_DEFINITION,
  ITEM_HAS_WITHOUT_QUESTION,
  COMPANY_GROUP_BULK_INSERT_EXCEPTION;

  @Override
  public String getMessageKey() {
    return "error.message." + getEnumCode();
  }
}
