package com.gastroblue.model.enums;

import com.gastroblue.commons.helper.exception.model.base.ErrorCodeBase;

public enum ErrorCode implements ErrorCodeBase {
  USER_NOT_FOUND,
  USER_ALREADY_EXISTS,
  COMPANY_NOT_FOUND,
  COMPANY_GROUP_NOT_FOUND,
  EULA_CONTENT_NOT_FOUND,
  COMPANY_GROUP_PRODUCT_NOT_FOUND,
  COMPANY_GROUP_PRODUCT_ALREADY_EXISTS,
  INVALID_MAIL_DOMAINS,
  COMPANY_PRODUCT_NOT_FOUND,
  COMPANY_PRODUCT_ALREADY_EXISTS,
  USER_NOT_ALLOWED_FOR_REGISTRATION,
  ACCESS_DENIED,
  INVALID_USERNAME_OR_PASSWORD,
  ADMINISTRATOR_REGISTRATION_DISABLED,
  PRODUCT_NOT_SELECTED,
  THERMOMETER_TRACKER_APP_NOT_ENABLED_FOR_COMPANY_GROUP,
  FORMFLOW_APP_NOT_ENABLED_FOR_COMPANY_GROUP,
  COMPANY_PRODUCT_LICENSE_EXPIRED,
  LICENSE_USER_LIMIT_EXCEEDED,
  COMPANY_PRODUCT_NOT_ACTIVE,
  PRODUCT_NOT_ALLOWED_FOR_REGISTRATION,
  USER_NOT_ELIGIBLE_EMAIL,
  USER_NOT_ELIGIBLE_SUPERVISOR_OR_ABOVE;

  @Override
  public String code() {
    return name();
  }
}
